export const ERROR_CODES = {
  EXTRACTOR_UNSUPPORTED_URL: "EXTRACTOR_UNSUPPORTED_URL",
  EXTRACTOR_UPSTREAM_CHANGE: "EXTRACTOR_UPSTREAM_CHANGE",
  EXTRACTOR_NO_FORMATS: "EXTRACTOR_NO_FORMATS",
  ACCESS_RESTRICTED_CONTENT: "ACCESS_RESTRICTED_CONTENT",
  ACCESS_GEO_BLOCKED: "ACCESS_GEO_BLOCKED",
  ACCESS_DRM_PROTECTED: "ACCESS_DRM_PROTECTED",
  DOWNLOAD_HTTP_RANGE_UNSUPPORTED: "DOWNLOAD_HTTP_RANGE_UNSUPPORTED",
  DOWNLOAD_URL_EXPIRED: "DOWNLOAD_URL_EXPIRED",
  STORAGE_QUOTA_PRECHECK_FAILED: "STORAGE_QUOTA_PRECHECK_FAILED",
  STORAGE_QUOTA_EXCEEDED: "STORAGE_QUOTA_EXCEEDED",
  MUX_INPUT_TOO_LARGE: "MUX_INPUT_TOO_LARGE",
  MUX_CODEC_INCOMPATIBLE: "MUX_CODEC_INCOMPATIBLE",
  MUX_FFMPEG_FAILURE: "MUX_FFMPEG_FAILURE",
  WORKER_TERMINATED_RECOVERED: "WORKER_TERMINATED_RECOVERED",
  WORKER_TERMINATED_UNRECOVERABLE: "WORKER_TERMINATED_UNRECOVERABLE",
  STATE_CORRUPTED: "STATE_CORRUPTED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface RuntimeErrorPayload {
  code: ErrorCode;
  message: string;
}
